/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#ffefee",
        "primary-fixed": "#6e9fff",
        "on-secondary-fixed": "#160bae",
        "error-dim": "#9f0519",
        "on-surface-variant": "#595c5e",
        "on-tertiary-fixed": "#270048",
        "on-background": "#2c2f31",
        "on-error-container": "#570008",
        "on-tertiary": "#fbefff",
        "surface-bright": "#f5f7f9",
        "on-primary-fixed-variant": "#002a62",
        "inverse-on-surface": "#9a9d9f",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#cdcdff",
        "tertiary-fixed": "#ce9bff",
        "secondary-fixed": "#cdcdff",
        "inverse-primary": "#4d8eff",
        "on-primary": "#f0f2ff",
        "on-primary-container": "#002150",
        "error-container": "#fb5151",
        "surface-container-low": "#eef1f3",
        "tertiary-container": "#ce9bff",
        "inverse-surface": "#0b0f10",
        "on-secondary": "#f4f1ff",
        "surface-container": "#e5e9eb",
        "surface-variant": "#d9dde0",
        "primary-container": "#6e9fff",
        "on-tertiary-container": "#4a0080",
        "background": "#f5f7f9",
        "secondary": "#4647d3",
        "tertiary-fixed-dim": "#c488ff",
        "on-tertiary-fixed-variant": "#560094",
        "on-primary-fixed": "#000000",
        "surface-container-highest": "#d9dde0",
        "error": "#b31b25",
        "tertiary-dim": "#740ec2",
        "primary-fixed-dim": "#5391ff",
        "surface-dim": "#d0d5d8",
        "on-secondary-fixed-variant": "#3a3ac8",
        "secondary-dim": "#3939c7",
        "surface": "#f5f7f9",
        "tertiary": "#8126cf",
        "surface-tint": "#0057bd",
        "surface-container-high": "#dfe3e6",
        "secondary-fixed-dim": "#bdbeff",
        "outline-variant": "#abadaf",
        "primary-dim": "#004ca6",
        "on-surface": "#2c2f31",
        "on-secondary-container": "#2f2ebf",
        "primary": "#0057bd",
        "outline": "#747779"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      }
    },
  },
  plugins: [],
}
