/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#658eff",
        "surface-container-highest": "#dadddf",
        "primary-container": "#7b9cff",
        "surface-variant": "#dadddf",
        "on-secondary-fixed": "#430097",
        "on-error-container": "#570008",
        "surface": "#f5f6f7",
        "secondary-container": "#dcc9ff",
        "on-secondary-container": "#5b00c7",
        "tertiary-dim": "#802d7d",
        "on-surface-variant": "#595c5d",
        "on-surface": "#2c2f30",
        "error-container": "#fb5151",
        "error": "#b31b25",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#9b9d9e",
        "outline": "#757778",
        "secondary-fixed-dim": "#d0b8ff",
        "primary": "#0050d4",
        "secondary": "#702ae1",
        "secondary-fixed": "#dcc9ff",
        "inverse-primary": "#618bff",
        "on-error": "#ffefee",
        "tertiary-container": "#fe9cf4",
        "surface-bright": "#f5f6f7",
        "surface-tint": "#0050d4",
        "surface-dim": "#d1d5d7",
        "surface-container-high": "#e0e3e4",
        "surface-container": "#e6e8ea",
        "on-tertiary-fixed-variant": "#711f6f",
        "on-tertiary-fixed": "#480049",
        "on-tertiary-container": "#661466",
        "on-primary-container": "#001e5a",
        "primary-fixed": "#7b9cff",
        "on-secondary": "#f8f0ff",
        "inverse-surface": "#0c0f10",
        "on-primary": "#f1f2ff",
        "primary-dim": "#0046bb",
        "surface-container-low": "#eff1f2",
        "background": "#f5f6f7",
        "on-secondary-fixed-variant": "#6514d6",
        "error-dim": "#9f0519",
        "outline-variant": "#abadae",
        "tertiary-fixed": "#fe9cf4",
        "on-primary-fixed-variant": "#00266e",
        "tertiary": "#8e3a8a",
        "on-background": "#2c2f30",
        "on-tertiary": "#ffeef8",
        "on-primary-fixed": "#000000",
        "tertiary-fixed-dim": "#ef8fe5"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Inter"],
        "label": ["Inter"]
      }
    },
  },
  plugins: [],
}
